name       : dolphin
version    : 17.04.2
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.04.2/src/dolphin-17.04.2.tar.xz : 45ac5454ec6f2e1382ab250be16871a3184804b91f23839a7ec4d8f4b972a0f9
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
summary    : KDE file manager focusing on usability
description: |
    Dolphin is a file manager focusing on usability. Focusing on usability means that features are discoverable and efficient to use.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Core)
    - baloo-widgets-devel
    - extra-cmake-modules
    - kbookmarks-devel
    - kcmutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kparts-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - solid-devel
rundeps    :
    - kinit
    - kio-extras
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
