name       : dolphin
version    : 19.08.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/dolphin-19.08.0.tar.xz : fd44714541ae7082d4615e441242afdba2d7810a373bfc8c3e64ff5c7db0a0f0
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE file manager focusing on usability
description: |
    Dolphin is a file manager focusing on usability. Focusing on usability means that features are discoverable and efficient to use.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(libKActivities)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Core)
    - baloo-widgets-devel
    - extra-cmake-modules
    - kbookmarks-devel
    - kcmutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - kparts-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - solid-devel
rundeps    :
    - ffmpegthumbs
    - kdialog
    - kio-extras
    - ruby
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
