name       : dolphin
version    : 20.04.2
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/dolphin-20.04.2.tar.xz : 37e4c1510227112365418cacccabc6d535fb0880e182a2341bfe00d585d14fb2
homepage   : https://kde.org/applications/system/org.kde.dolphin
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE file manager focusing on usability
description: |
    Dolphin is a file manager focusing on usability. Focusing on usability means that features are discoverable and efficient to use.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(libKActivities)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Core)
    - baloo-widgets-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kinit-devel
    - knewstuff-devel
    - knotifications-devel
    - kparts-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
rundeps    :
    - ffmpegthumbs
    - kdialog
    - kio-extras
    - ruby
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
