name       : dolphin
version    : 21.08.2
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/dolphin-21.08.2.tar.xz : 4256d5077cc83f8025838b59f4dafabb16ed800bcb58761f312f6a8cdcc551a1
homepage   : https://kde.org/applications/system/org.kde.dolphin
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE file manager focusing on usability
description: |
    Dolphin is a file manager focusing on usability. Focusing on usability means that features are discoverable and efficient to use.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(phonon4qt5)
    - baloo-devel
    - baloo-widgets-devel
    - kactivities-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kparts-devel
rundeps    :
    - ffmpegthumbs
    - kdialog
    - ruby
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
